### ISSUE TITLE
TSV file

### ISSUE THREAD

**Issue by CristianUNR** [chg60/phammseqs#3]
Hi! 
Please how can I obtain the genome-to-pham-to-translation mappings in a tsv table format that is required for PhamClust? 
Thanks in advance

**Comment by chg60** [comment]
Hello!

If you run PhaMMseqs with the `-p`/`--pangenome` argument, it will produce a series of additional output files, including one called 'strain_genes.tsv' - this one can be used by PhamClust. Note that for this to work properly, you need to provide your input genes as _N_ FASTA files, one file per genome represented by your dataset.

I'm going to close this issue for now, but please feel free to re-open if you encounter any trouble.
